### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by aforren1** [aforren1/hand#2]
- [x] Multiplexer code cleanup
 - [x] PGA code cleanup
 - [x] User message handling
 - [x] User instructions (compilation via Arduino/Teensyduino, PlatformIO)
 - [x] Documentation
 - [x] Resolve ambiguity in types (e.g. prefer `uint16_t` to `unsigned int`)
